### ISSUE TITLE
Error when closing

### ISSUE THREAD

**Issue by arkag** [thmsbfft/oryoki#10]
Clicking red "close" button results in the following pop up.

```
Uncaught Exception:
TypeError: Cannot read property 'close' of null
    at Oryoki.closeWindow (/Users/ishmael/Downloads/Archives/Oryoki.app/Contents/Resources/app/main.js:1301:20)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.<anonymous> (/Users/ishmael/Downloads/Archives/Oryoki.app/Contents/Resources/electron.asar/browser/api/web-contents.js:156:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

What information do you need from me?

**Comment by thmsbfft** [comment]
What OS version are you on? And, does this happen after launching the app,
closing the first window or after having opened/closed several? I'll look
into it.

**Comment by arkag** [comment]
Seems to be after opening and closing several. I opened 4 and then closed 3 without issue. The original window threw the error. The original window closed after some time of sitting, too.

**Comment by arkag** [comment]
Just reproduced, and realized I forgot to tell you my OS version: 10.11.5

Side note: CMD-W closes all without issue.

**Comment by thmsbfft** [comment]
Gotcha. Good catch. I'm emulating the system traffic lights so that's probably something related.

**Comment by arkag** [comment]
What do you mean by emulating them? Not well versed in development, especially in regards to Apple software.

**Comment by thmsbfft** [comment]
I'm not using the system's traffic lights, just creating a bunch of buttons and wiring them to the close() minimize() fullscreen() hooks that Electron provides (that's so I can hide/show the entire title bar) – meaning I have to handle windows myself, which obviously I didn't do 100% right, ah!
