### ISSUE TITLE
Mouse movement when screen recording

### ISSUE THREAD

**Issue by mylespalmer** [thmsbfft/oryoki#12]
A feature suggestion (tweak!) would be that when recording the webpage you're enable to toggle on / off the mouse cursor.

Usually I would find that I don't want the cursor, but having just recorded a few websites that don't have the most obvious navigational points it becomes quite difficult to understand how things are functioning.

**Comment by thmsbfft** [comment]
Hey there – recording the mouse cursor is planned for a future version :)

**Comment by mylespalmer** [comment]
Great :), look forward to it.

**Comment by thmsbfft** [comment]
New duplicate with some spec ideas on #30. Closing this one.
