### ISSUE TITLE
Minimum window width and changing window dimensions

### ISSUE THREAD

**Issue by travisk-codes** [thmsbfft/oryoki#18]
- Using the mouse, the minimum width of a window appears to be 600px
- There appears to be no minimum width when using cmd+alt+M
- If the window width is set to less than 600px, resizing the window with the mouse will cause the window to jump back to 600px

Not sure what kind of behavior you would prefer, but if you were to ask me, I'd suggest a much smaller minimum (maybe like 100px for cute tiny web apps?) and cap the cmd+alt+M feature to that number.

Love what you have so far!

**Comment by thmsbfft** [comment]
Hey, thanks for posting. The current minimum dimensions for windows are 600x350. That said the window helper, when manually setting dimensions, doesn't account for these – agree it should be capped to that.

Having windows work below these dimensions require a bit of optim on the UI. I'll get on that. Do you have a specific use case for a 100x100 window?

**Comment by travisk-codes** [comment]
I didn't have any specific use case in mind, but I frequently will use a small window for a stopwatch/timer or something, and it's frequently these smaller web apps that I'd prefer to use to save as much screen real-estate as possible (why I love this project!)

Thanks!

**Comment by thmsbfft** [comment]
Oy! Should be fixed in 0.1.0. Minimum window dimensions now are 200x200.
