### ISSUE TITLE
Feature request: other search engines

### ISSUE THREAD

**Issue by acstll** [thmsbfft/oryoki#20]
Hi there,

the app is beautiful, thanks for building it.

I wanted to ask if it was possible to add the option to change the search engine (I like using duckduckgo, for instance). I think that could be part of the preferences, and then use it here…?

https://github.com/thmsbfft/oryoki/blob/0a8e302f5d15446fdccd871df52dc06b9418ac3b/src/js/renderer/Omnibox.js#L123

**Comment by thmsbfft** [comment]
Hi – & thanks :)

Changing the default search engine will be part of the Omnibox overhaul. That'll include a keyword based search and a customizable dictionary; e.g. typing `wiki oryoki` will search wikipedia for the term.

**Comment by acstll** [comment]
Brilliant, let me know if you can use some help.

I got some more comments, should I just write them down below and you can decide if you want to make separate issues out of them?

Thank you!

**Comment by thmsbfft** [comment]
Sure, write away! Happy to hear all suggestions.

**Comment by acstll** [comment]
So here it goes:

Buggy:
- I would swip "Edit" and "File" on the OS menu bar ("File" usually goes first)

Nice to have:
- New windows could use the current window's size after doing Cmd+click to open link in new window (or at least offer that as an option in preferences)
- A list of open windows should be under the "Window" item in the menu bar
- It'd be great to have a shortcut to switch between open windows, one to go through all of them (in order or opening) and one to swap back and forth between current and previous…

Really personal:
- I would forget about "Bookmarks" if it's not like super brilliantly implemented
- I would focus on stability and tiny usability details for a first "final" release (I really love it as it is now)

Thanks again!

**Comment by thmsbfft** [comment]
That's awesome! Opening separate issues for all these. Great comments, thanks for taking the time. Trying to wrap my head around the window switching: do you have a software in mind that uses that? Wondering if it should just change the focus or center the window / hide the previous, etc.

Also agree on bookmarks - tough problem, and there's more things to fix before moving on to that. While I have you, mind if I bounce some ideas off you?

**Comment by acstll** [comment]
No problem!

> Trying to wrap my head around the window switching: do you have a software in mind that uses that?

[Visual Studio Code](https://code.visualstudio.com), for example, there's Ctrl+Tab, to switch between 2 files. You open file A, then open file B, press Ctrl+Tab and go back to A, Ctrl-Tab again and back to B and so on… really handy sometimes. I would just change the focus.

Then for going through open windows, I'd suggest using Cmd+alt+<arrow> just like you change tabs in Firefox. I'm currently using the "Exposé" gesture (three fingers down) to switch between open windows…

> While I have you, mind if I bounce some ideas off you?

Not at all!

**Comment by thmsbfft** [comment]
OK, will check these. 👍 

As for ideas, I am looking at this set now (taken from the [to-do](https://github.com/thmsbfft/oryoki#to-do)):
- **Local server wizard**
  This would allow File > Open to launch a local server before loading a project folder, & potentially also look for changes in that folder and reload the thing. To me, that's useful when you want to quick-edit a sketch or check out an old project easily, but with build systems around today I'm not sure of the value of this. Is that something you'd use?
- **CSS Themes/Stylesheet**
  So, yeah, that would basically imply having a separate stylesheet that you can edit – though I'm wondering if a simple json containing color values for the app wouldn't be better. What are you thoughts on this? I have been asked to make the omnibox overlay transparent, e.g., so themes would solve that.
- **Mini Console**
  Idk if you've seen but there's a mini console that allows you to inject JS into the webview. It does basically nothing else right now, but I feel there's something cool about a small, super quick access console, right? I'm thinking of adding an fps meter in there - anything else comes to mind?

Alright that's it. Been toying with these a bit but any comment is good. Cheers!

**Comment by thmsbfft** [comment]
Closing to keep the project clean, but I have notes on all that.

**Comment by acstll** [comment]
@thmsbfft no problem. It's funny I just yesterday downloaded version 0.0.4 (I had been not using Oryoki for a while), and I love the new stuff. Thank you! (I'm sorry I haven't had time to be more involved in giving feedback to the project.)
