### ISSUE TITLE
Shortcut to Set Window Size(s)

### ISSUE THREAD

**Issue by mtclmn** [thmsbfft/oryoki#25]
Would ❤️  a keyboard shortcut to set window size.

Use case: I like to take screenshots at certain browser sizes, and since Oryoki is perfect for taking nice screenshots, it would be awesome to set a shortcut for a certain size, or an array of sizes.

**Comment by thmsbfft** [comment]
Right now you can set window size with `cmd+alt+m`. This doesn't account for pixel density yet so on a retina screen for example a 800x600 window will give you 1600x1200 screenshots. 

In the future I'll be adding some templates. Hope this helps!
