### ISSUE TITLE
Keyboard Interactions don't work after cmd-tab

### ISSUE THREAD

**Issue by danielma** [thmsbfft/oryoki#28]
**Problem**

When I cmd-tab and select Oryoki, keyboard interactions don't work until I click on the browser window. Electron shortcuts work (like `cmd-n`), but the up/down arrow don't work

I normally use Oryoki with no title bar, but I have the same problem with the title bar visible

**System Info**

OS: OSX 10.11.4
Oryoki version: 0.0.3 (0.0.3)

**Comment by thmsbfft** [comment]
Hey, thanks for pointing that out. Should be fixed in the next release.

I assume you're mentioning the up/down arrow used to set the window size – if so, there was something preventing keyboard shortcuts from being used when (fixed in a07535f). Or was it something else, more global?
