### ISSUE TITLE
Navigating Ajax-pages

### ISSUE THREAD

**Issue by westn** [thmsbfft/oryoki#29]
When navigating around e.g. youtube, after every request / new page the search bar keeps popping up. This issue first came to me after updating to 0.0.4

Tell me if you need more info

**Comment by thmsbfft** [comment]
Okay, seems to be related to cross origin loading (e.g. ads, loads of ads) triggering a `webview-crashed` event. Fixed on /dev for now until I can investigate a bit more. Thanks :v:
