### ISSUE TITLE
~5 sec delay before I can click on link

### ISSUE THREAD

**Issue by cjdunn** [thmsbfft/oryoki#32]
If I load a page, for example https://www.google.com/#q=oryoki+browser, I can't click on a link for about 5 seconds until the page fully loads, even thought the page is visible. This happens every time, even if I've already visited this page. All other browsers I've tried, (Chrome, FF, Safari) allow me to click as soon as the page is visible, even the first time. It sounds like a small thing, but happens enough become quite annoying. 

Otherwise, I love this browser and the minimal interface. Thanks so much for your consideration!

**Comment by thmsbfft** [comment]
Curious to hear if that happens on any page (try [oryoki.io](http://oryoki.io)) or only Google.com or Google requests via the omnibox. Thanks for reporting, I'll look into it – completely see how that can be super annoying.

**Comment by cjdunn** [comment]
It looks like this is on Google request via the omnibox and also Google.com direct searches. I don't see this behavior oryoki.io or even on bing.com or amazon.com or other pages full of links. Thanks for looking into it.

**Comment by thmsbfft** [comment]
Ok, seems like something on Google is freezing the renderer process - could be intense computation happening in the background or requesting something the sandboxed webview doesn't allow.

**Comment by thmsbfft** [comment]
That was the latter. Should be fixed in 723d937 (for next update).
