### ISSUE TITLE
textarea:focus or input:focus disables "naviagate back/forward" shortcuts

### ISSUE THREAD

**Issue by cjdunn** [thmsbfft/oryoki#33]
Perhaps this is related to using the arrow keys (⌘← and ⌘→) for shortcuts? Would this be any different if the shortcuts ⌘[ and ⌘] were also allowed for navigate back/forward? Chrome works with both. When I try in Chrome, I get the same problem when using ⌘← and ⌘→ from textarea or input, but there's no issue when using ⌘[ and ⌘]. Would you consider allowing both shortcuts? Or is there a way to set custom shortcuts? Thanks.

**Comment by thmsbfft** [comment]
Good catch. As of now there's no way of setting multiple shortcuts for one command in the menus without a workaround (https://github.com/electron/electron/issues/4758) so I'll switch over to `⌘[` and `⌘]`. Fixed in 791d7d0.
