### ISSUE TITLE
Javascript error when opening v0.2.0

### ISSUE THREAD

**Issue by robinjungers** [thmsbfft/oryoki#35]
Hi,
I'm having a Javascript error when opening the application (directly downloaded from oryoki.io), then no window shows up.
I'm on Sierra 10.12.6.

<img width="420" alt="p" src="https://user-images.githubusercontent.com/11521619/30095079-2dc64df0-930b-11e7-9748-337035712564.png">

**Comment by thmsbfft** [comment]
Hello—I think you may be updating from an early version. Try erasing the preferences folder (`~/Library/Application Support/Oryoki`) and restarting the app. Let me know if that works.

Oryoki looks for the field `model_version` in the `oryoki-preferences.json` to check against factory settings. The field didn't exist in early versions, hence the error.

**Comment by robinjungers** [comment]
Problem solved, indeed !
I love the app, keep up the good work.
