### ISSUE TITLE
Change the default location for ffmpeg?

### ISSUE THREAD

**Issue by almosnow** [thmsbfft/oryoki#37]
Dear everyone,

I compiled ffmpeg from source into a different directory than usual.

Is there a way to tell Oryoki to look for it there?

almosnow

**Comment by thmsbfft** [comment]
Hi there—no plan for that at the moment, but we could potentially add a preference to set ffmpeg's path. 

Another options would be to allow adding a custom value to the process' `$PATH` (see [here](https://github.com/thmsbfft/oryoki/blob/dev/app/index.js#L2)). Would this help?

**Comment by almosnow** [comment]
Ok, let me try that out.

Thanks.
