### ISSUE TITLE
User agent spoofing

### ISSUE THREAD

**Issue by jondashkyle** [thmsbfft/oryoki#41]
I use Oryoki oftentimes in a narrow “mobile” proportion. Some sites check user agent to determine if a mobile view should be used. Would be cool to add a menu option which lets you adjust that!

1. https://electronjs.org/docs/api/webview-tag#useragent

**Comment by thmsbfft** [comment]
I've wanted that for a while. Should we just provide a checkbox to "✓ Request Mobile Site", or a variety of possible user agents? Not sure about use cases for the later.

**Comment by jondashkyle** [comment]
Definitely think the “Request Mobile Site” toggle is the way to go!

**Comment by jondashkyle** [comment]
https://github.com/thmsbfft/oryoki/pull/42 :tada:
