### ISSUE TITLE
CTRL+Enter Shortcut for Completing Web Addresses

### ISSUE THREAD

**Issue by 1deadpixl** [thmsbfft/oryoki#8]
Since the omnibox in Oryoki is so simple, it would be nice to have some keyboard shortcuts to enhance query input. Chrome supports completing the URL with a ".com" prefix by pressing `ctrl+enter`. I'd like to suggest adding that one plus additional modifiers like `alt` and `shift` to do more completions like ".org" and ".net".

**Comment by thmsbfft** [comment]
Right now using `tab` allows to change to a "feeling lucky" search, so that kinda does the `ctrl+enter` job.
`alt` & `shit` sounds a bit confusing - need to feel it out first. Also, the omnibox will be revised with more functionality in the future (`<keyword> query` kinda thing).

**Comment by 1deadpixl** [comment]
OK, I see what you mean with the "feeling lucky" search. It's direct for most sites, but it's not clear what's going to load until you press `enter`, which is a bit unsettling. You can try out the keyboard shortcuts I'm suggesting in Firefox. Check out the [Miscellaneous section](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_miscellaneous) of their keyboard shortcuts list—they use combinations of `shift` and `cmd`.

**Comment by thmsbfft** [comment]
0.1.0 introduces a ctrl+enter shortcut to a _lucky search_. Works nicely as an alternative, so I'm closing for now.
